title: Critical Conversations
tagline: Advancing a culture of freedom and inclusivity
description: ""
baseurl: ""

markdown: kramdown
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - README.md
  - "*.log"
